WITH CUSTOMER_ORDERS AS(
    SELECT
    CUSTOMER_ID,
    REGION,
    COUNT(ORDER_ID) AS ORDER_COUNT
    FROM SALES_ANALYSIS.SALES
    GROUP BY CUSTOMER_ID,REGION
)
SELECT 
    REGION,
    COUNT(CASE WHEN ORDER_COUNT>1 THEN 1 END) *100.0/COUNT(*)
    AS RETENTION_PERCENTAGE
FROM CUSTOMER_ORDERS
GROUP BY REGION;