SELECT 
    REGION,
    PRODUCT_ID,
    CASE
        WHEN MONTH(ORDER_DATE) IN (12,1,2) THEN 'WINTER'
        WHEN MONTH(ORDER_DATE) IN (3,4,5) THEN 'SPRING'
        WHEN MONTH(ORDER_DATE) IN (6,7,8) THEN 'SUMMER'
        ELSE 'FALL'
    END AS SEASON,
    SUM(QUANTITY) AS TOTAL_SOLD
FROM SALES_ANALYSIS.SALES
GROUP BY REGION, PRODUCT_ID, SEASON
ORDER BY REGION, SEASON, TOTAL_SOLD DESC;